In [1]:
from typing import Any, Callable, Dict, Iterable, Optional, Text, Tuple, Union

from flax import linen as nn
import jax
import jax.numpy as jnp
import jax.random as jr

import math

from maskgit.nets.maskgit_transformer import Mlp, Bias, Embed, MlmLayer

LAYERNORM_EPSILON = 1e-12  # Layer norm from BERT

InitializerType = Callable[[jnp.ndarray, Iterable[int], jnp.dtype], jnp.ndarray]

In [178]:
# Testing Original hollow transformer + RoPE
class Dropout1d(nn.Module):

  dropout_rate: float = 0.0

  def __call__(self, x, deterministic=True):
    if (self.dropout_rate > 0.0) and not deterministic:
      drop = jax.random.bernoulli(
          self.make_rng('dropout'),
          1 - self.dropout_rate,
          (x.shape[0], 1, x.shape[-1]),
      )
      x = x * drop / (1 - self.dropout_rate)
    return x

def precompute_freqs_cis(dim, end, theta: float = 10000.0):
  freqs = 1.0 / (theta ** (jnp.arange(0, dim, 2)[: (dim // 2)] / dim))
  t = jnp.arange(end)
  freqs = jnp.outer(t, freqs)
  freqs_cos = jnp.cos(freqs)
  freqs_sin = jnp.sin(freqs)
  return freqs_cos, freqs_sin

def reshape_for_broadcast(freqs_cis, x):
  ndim = x.ndim
  assert 1 < ndim
  assert freqs_cis.shape == (x.shape[1], x.shape[-1])
  shape = [d if i == 1 or i == ndim - 1 else 1 for i, d in enumerate(x.shape)]
  return freqs_cis.reshape(shape)


def jax_unstack(x, axis=0):
  return [
      jax.lax.index_in_dim(x, i, axis, keepdims=False)
      for i in range(x.shape[axis])
  ]

def apply_rotary_emb(x, freqs_cos, freqs_sin):
  # reshape x to match the complex representation
  # [bs, seq_len, n_head, head_dim // 2]
  x_r, x_i = jax_unstack(x.reshape(x.shape[:-1] + (-1, 2)), -1)

  # reshape freqs_cos and freqs_sin for broadcasting
  # [1, seq_len, 1, head_dim // 2]
  freqs_cos = reshape_for_broadcast(freqs_cos, x_r)
  freqs_sin = reshape_for_broadcast(freqs_sin, x_r)

  # apply rotation using real numbers
  x_out_r = x_r * freqs_cos - x_i * freqs_sin
  x_out_i = x_r * freqs_sin + x_i * freqs_cos

  # flatten last two dimensions
  # [bs, seq_len, n_head, head_dim // 2, 2] -> [bs, seq_len, n_head, head_dim]
  x_out = jnp.stack([x_out_r, x_out_i], axis=-1).reshape(
      x_out_r.shape[:3] + (-1,)
  )
  return x_out

# Not used if n_heads == n_kv_heads (n_rep == 1)
def repeat_kv(x, n_rep):
  bs, slen, n_kv_heads, head_dim = x.shape
  if n_rep == 1:
    return x
  return jnp.tile(x[:, :, :, None, :], [1, 1, 1, n_rep, 1]).reshape(
      bs, slen, n_kv_heads * n_rep, head_dim
  )

class MaskedAttentionWithRoPE(nn.Module):
  """
  Attention that takes in an additive mask, with the "causal" flag removed.
  Everything else is identical with the original MD4 implementation
  """

  dim: int
  n_heads: int
  n_kv_heads: int = None
  dropout_rate: float = 0.0
  qkv_bias: bool = True # In line with flax implementation

  def setup(self):
    self._n_kv_heads = (
        self.n_heads if self.n_kv_heads is None else self.n_kv_heads
    )
    assert self.n_heads % self._n_kv_heads == 0
    self.n_rep = self.n_heads // self._n_kv_heads
    self.head_dim = self.dim // self.n_heads
    self.wq = nn.Dense(self.n_heads * self.head_dim, use_bias=self.qkv_bias)
    self.wk = nn.Dense(self._n_kv_heads * self.head_dim, use_bias=self.qkv_bias)
    self.wv = nn.Dense(self._n_kv_heads * self.head_dim, use_bias=self.qkv_bias)
    self.wo = nn.Dense(self.dim, use_bias=False)
    if self.dropout_rate > 0.0:
      self.attn_dropout = nn.Dropout(self.dropout_rate)
      self.resid_dropout = Dropout1d(self.dropout_rate)

  def __call__(self, x_q, x_kv, attn_mask, freqs_cos_q, freqs_sin_q, 
    freqs_cos_kv=None, freqs_sin_kv=None, deterministic=True):
    bsz, seqlen_q, _ = x_q.shape
    _, seqlen_kv, _ = x_kv.shape

    # QKV
    xq, xk, xv = self.wq(x_q), self.wk(x_kv), self.wv(x_kv)
    xq = xq.reshape(bsz, seqlen_q, self.n_heads, self.head_dim)
    xk = xk.reshape(bsz, seqlen_kv, self._n_kv_heads, self.head_dim)
    xv = xv.reshape(bsz, seqlen_kv, self._n_kv_heads, self.head_dim)

    # RoPE relative positional embeddings
    xq = apply_rotary_emb(xq, freqs_cos_q, freqs_sin_q)
    
    freqs_cos_kv = freqs_cos_q if freqs_cos_kv is None else freqs_cos_kv
    freqs_sin_kv = freqs_sin_q if freqs_sin_kv is None else freqs_cos_kv
    xk = apply_rotary_emb(xk, freqs_cos_kv, freqs_sin_kv)

    # grouped multiquery attention: expand out keys and values
    xk = repeat_kv(xk, self.n_rep)
    xv = repeat_kv(xv, self.n_rep)

    # make heads into a batch dimension
    xq = xq.swapaxes(1, 2)  # (bs, n_heads, seqlen_q, head_dim)
    xk = xk.swapaxes(1, 2)
    xv = xv.swapaxes(1, 2)

    scores = jnp.matmul(xq, xk.swapaxes(2, 3)) / math.sqrt(self.head_dim)

    # Assuming attn_mask already has the right shape
    scores = (
          scores + attn_mask
      )  # (bs, n_heads, seqlen_q, seqlen_kv)

    scores = nn.softmax(scores, axis=-1)
    if self.dropout_rate > 0.0:
      scores = self.attn_dropout(scores, deterministic=deterministic)
    output = jnp.matmul(scores, xv)  # (bs, n_heads, seqlen_q, head_dim)

    # restore time as batch dimension and concat heads
    output = output.swapaxes(1, 2).reshape(bsz, seqlen_q, -1)

    # final projection into the residual stream
    output = self.wo(output)
    if self.dropout_rate > 0.0:
      output = self.resid_dropout(output, deterministic=deterministic)
    return output

class CausalAttention(nn.Module):
  """Attention layer that is part of each Transformer layer."""
  hidden_size: int
  hidden_dropout_prob: float
  num_attention_heads: int
  attention_probs_dropout_prob: float
  hidden_dropout_prob: float
  initializer_fn: InitializerType

  @nn.compact
  def __call__(self, q: jnp.ndarray, kv: jnp.ndarray,
               attention_mask: jnp.ndarray,
               deterministic: bool) -> jnp.ndarray:

    attention_output = nn.attention.MultiHeadAttention(
        num_heads=self.num_attention_heads,
        qkv_features=self.hidden_size,
        out_features=None,
        dropout_rate=self.attention_probs_dropout_prob,
        deterministic=deterministic,
        kernel_init=self.initializer_fn,
        bias_init=jax.nn.initializers.zeros,
        name='multi_head_attention',
    )(q, kv, kv, mask=attention_mask)

    attention_output = nn.Dropout(rate=self.hidden_dropout_prob)(
        attention_output, deterministic=deterministic)
    attention_output = nn.LayerNorm(
        epsilon=LAYERNORM_EPSILON, name='attention_output_ln')(
            attention_output + q)

    return attention_output

class GenericTransformerLayer(nn.Module):
  """A single Transformer layer."""
  intermediate_size: int
  hidden_size: int
  hidden_dropout_prob: float
  num_attention_heads: int
  attention_probs_dropout_prob: float
  initializer_fn: InitializerType

  @nn.compact
  def __call__(self, q: jnp.ndarray, kv: jnp.ndarray, mask: jnp.ndarray,
               freqs_cos: jnp.ndarray, freqs_sin: jnp.ndarray,
               freqs_cos_kv: jnp.ndarray=None, freqs_sin_kv: jnp.ndarray=None,
               deterministic: bool=True) -> jnp.ndarray:
      
    # attention_output = CausalAttention(
    #     hidden_size=self.hidden_size,
    #     hidden_dropout_prob=self.hidden_dropout_prob,
    #     num_attention_heads=self.num_attention_heads,
    #     attention_probs_dropout_prob=self.attention_probs_dropout_prob,
    #     initializer_fn=self.initializer_fn)(
    #         q=q, kv=kv, attention_mask=mask,
    #         deterministic=deterministic)

    # Note that this function from MD4 applies dropout
    # but not the residual connection and layer norm
    attention_output = MaskedAttentionWithRoPE(
        dim=self.hidden_size,
        n_heads=self.num_attention_heads,
        dropout_rate=self.attention_probs_dropout_prob,
        qkv_bias=True)(q, kv, mask,
            freqs_cos, freqs_sin, 
            freqs_cos_kv=freqs_cos_kv, freqs_sin_kv=freqs_sin_kv,
            deterministic=deterministic)
      
    # Apply layer norm and residual connection
    attention_output = nn.LayerNorm(
        epsilon=LAYERNORM_EPSILON, name='attention_output_ln')(attention_output + q)

    layer_output = Mlp(
        hidden_size=self.hidden_size,
        hidden_dropout_prob=self.hidden_dropout_prob,
        intermediate_size=self.intermediate_size,
        initializer_fn=self.initializer_fn)(
            attention_output=attention_output, deterministic=deterministic)

    return layer_output

class HollowTransformer(nn.Module):
  """Hollow transformer modified from BERT."""
  vocab_size: int
  hidden_size: int = 768
  num_hidden_layers: int = 12
  num_attention_heads: int = 12
  intermediate_size: int = 3072
  hidden_dropout_prob: float = 0.1
  attention_probs_dropout_prob: float = 0.1
  max_position_embeddings: int = 256
  initializer_range: float = 0.02
  num_layers_per_mixed: int = 4 

  @nn.compact
  def __call__(self,
               input_ids: jnp.ndarray,
               t: float, # This is not currently used
               deterministic: bool = True) -> Dict[Text, jnp.ndarray]:

    B, L = input_ids.shape
    pad = jnp.zeros((B, 1))
    input_ids = jnp.concatenate([pad, input_ids, pad], axis=1)

    input_ids = input_ids.astype('int32')
    x = Embed(
        embedding_size=self.hidden_size,
        hidden_dropout_prob=self.hidden_dropout_prob,
        vocab_size=self.vocab_size,
        max_position_embeddings=self.max_position_embeddings + 2, # Including the padded values
        initializer_fn=truncated_normal(self.initializer_range),
        # use_position_embeddings=False
    )( # No positional embeddings because of the rotary position encoding
            input_ids=input_ids, deterministic=deterministic)

    key = jr.PRNGKey(0)
    # # Randomly permute the sequence after positional embeddings
    # rand_perm = jax.random.permutation(key, jnp.arange(L-2))
    # rand_perm = jnp.concatenate([jnp.array([0]), rand_perm + 1, jnp.array([L-1])], axis=0)
    # # Permute the sequence
    # x = jnp.concatenate([x[:,:1], x[:,1:-1][:,rand_perm], x[:,-1:]], axis=1)
      
    H = self.num_attention_heads
      
    freqs_cos, freqs_sin = precompute_freqs_cis(self.hidden_size // self.num_attention_heads, L+2)

    # Offset the two streams and initialize the mixed stream to None
    freqs_cos_f, freqs_sin_f = freqs_cos[:-2], freqs_sin[:-2]
    freqs_cos_b, freqs_sin_b = freqs_cos[2:], freqs_sin[2:]
    freqs_cos_m, freqs_sin_m = freqs_cos[1:-1], freqs_sin[1:-1]
    freqs_cos_m_kv = jnp.concatenate([freqs_cos_f, freqs_cos_b], axis=0)
    freqs_sin_m_kv = jnp.concatenate([freqs_sin_f, freqs_sin_b], axis=0)

    forward_mask = jnp.tril(jnp.ones((L+1, L+1)))
    backward_mask = jnp.triu(jnp.ones((L, L)))

    full_perm_matrix = jnp.eye(L+2)
    perm_matrix = jnp.eye(L-2)
    perm_matrix = jax.random.permutation(key, perm_matrix, axis=0)
    full_perm_matrix = full_perm_matrix.at[2:-2, 2:-2].set(perm_matrix)
    forward_mask = full_perm_matrix[1:, 1:] @ forward_mask @ full_perm_matrix[:-1, :-1].T
    backward_mask = full_perm_matrix[2:, 2:] @ backward_mask @ full_perm_matrix[:-2, :-2].T

    forward_mask = forward_mask[:-1,:-1]      
    forward_mask = jnp.tile(forward_mask[None, None], (B, H, 1, 1))
    backward_mask = jnp.tile(backward_mask[None, None], (B, H, 1, 1))

    # Different conventions between MD4 attention and linen.MultiHeadAttention
    forward_mask = jnp.where(forward_mask == 0, -jnp.inf, 0)
    backward_mask = jnp.where(backward_mask == 0, -jnp.inf, 0)
      
    mixing_mask = jnp.concatenate([forward_mask, backward_mask], axis=-1)   

    xf = x[:,:-2]
    xb = x[:,2:]
    xm = jnp.zeros_like(xf)
    
    for i in range(self.num_hidden_layers):
      fb_layer = GenericTransformerLayer(
          intermediate_size=self.intermediate_size,
          hidden_size=self.hidden_size,
          hidden_dropout_prob=self.hidden_dropout_prob,
          num_attention_heads=self.num_attention_heads,
          attention_probs_dropout_prob=self.attention_probs_dropout_prob,
          initializer_fn=truncated_normal(self.initializer_range))
    #   b_layer = GenericTransformerLayer(
    #       intermediate_size=self.intermediate_size,
    #       hidden_size=self.hidden_size,
    #       hidden_dropout_prob=self.hidden_dropout_prob,
    #       num_attention_heads=self.num_attention_heads,
    #       attention_probs_dropout_prob=self.attention_probs_dropout_prob,
    #       initializer_fn=truncated_normal(self.initializer_range))
      xf = fb_layer(q=xf, kv=xf, mask=forward_mask, 
                    freqs_cos=freqs_cos_f, freqs_sin=freqs_sin_f,
                    deterministic=deterministic)
      xb = fb_layer(q=xb, kv=xb, mask=backward_mask, 
                    freqs_cos=freqs_cos_b, freqs_sin=freqs_sin_b,
                    deterministic=deterministic)

      if (i + 1) % self.num_layers_per_mixed == 0:
        xm += xf + xb
        xfb = jnp.concatenate([xf, xb], axis=1)
        m_layer = GenericTransformerLayer(
          intermediate_size=self.intermediate_size,
          hidden_size=self.hidden_size,
          hidden_dropout_prob=self.hidden_dropout_prob,
          num_attention_heads=self.num_attention_heads,
          attention_probs_dropout_prob=self.attention_probs_dropout_prob,
          initializer_fn=truncated_normal(self.initializer_range))
        xm = m_layer(q=xm, kv=xfb, mask=mixing_mask, 
                    freqs_cos=freqs_cos_m, freqs_sin=freqs_sin_m,
                    freqs_cos_kv=freqs_cos_m_kv, freqs_sin_kv=freqs_sin_m_kv,
                    deterministic=deterministic)

    layer_output = xf #xm
    # layer_output = layer_output[:, jnp.argsort(rand_perm)]
    # # pdb.set_trace()
      
    word_embedding_matrix = self.variables['params']['Embed_0'][
        'word_embeddings']['embedding']
    logits = MlmLayer(
        hidden_size=self.hidden_size,
        initializer_fn=truncated_normal(self.initializer_range))(
            last_layer=layer_output, embeddings=word_embedding_matrix)

    # pdb.set_trace()
    # logits = logits[:, jnp.argsort(rand_perm)]
      
    return logits

In [191]:
L = 5
forward_mask = jnp.tril(jnp.ones((L+1, L+1)))

backward_mask = jnp.triu(jnp.ones((L, L)))
full_perm_matrix = jnp.eye(L+2)
perm_matrix = jnp.eye(L-2)
perm_matrix = jax.random.permutation(jr.PRNGKey(1), perm_matrix, axis=0)
full_perm_matrix = full_perm_matrix.at[2:-2, 2:-2].set(perm_matrix)
print(full_perm_matrix)
forward_mask = full_perm_matrix[1:, 1:] @ forward_mask @ full_perm_matrix[:-1, :-1].T
print(forward_mask)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 1. 1. 0.]
 [1. 1. 0. 0. 0. 0.]
 [1. 1. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1.]]


In [179]:
def truncated_normal(stddev: Union[float, jnp.ndarray], dtype=jnp.float32):

  def init(key: jnp.ndarray, shape: Iterable[int], dtype: jnp.dtype = dtype):
    return jax.random.truncated_normal(
        key=key, lower=-2, upper=2, shape=shape, dtype=dtype) * stddev

  return init

In [180]:
key = jr.PRNGKey(0)
jax.config.update("jax_debug_nans", True)
jax.config.update("jax_debug_infs", False)

k = 5
vocab_size = 1024
seq_len = 10
model = HollowTransformer(
  vocab_size = vocab_size + 1,
  hidden_size = k,
  num_hidden_layers = 6,
  num_attention_heads = 2,
  intermediate_size = 10,
  hidden_dropout_prob = 0.0,
  attention_probs_dropout_prob = 0.0,
  max_position_embeddings = seq_len + 1,
  initializer_range = 1.,#0.02
  num_layers_per_mixed = 3,
)

In [181]:
r = jax.random.permutation(jr.PRNGKey(0), jnp.arange(seq_len))

In [182]:
r

Array([2, 7, 9, 6, 0, 8, 1, 3, 4, 5], dtype=int32)

In [183]:
key, _ = jr.split(key)
input_sequence = jr.categorical(logits=jnp.ones((vocab_size,)), shape=(1, seq_len), key=key)
params = model.init(key, input_sequence, 0, True)

l = 2

out1 = model.apply(params, input_sequence, 0, True)
input_sequence = input_sequence.at[0, l].set((input_sequence[0, l] - 1) % vocab_size)
out2 = model.apply(params, input_sequence, 0, True)
print(jnp.sum(out1[0] - out2[0], axis=1))

[ 0.          0.6116098  -0.8164474  -2.2574513  -0.1124742  -0.04357862
  0.52571344  0.05162501  0.880664    1.1239864 ]


In [3]:
class CausalAttention(nn.Module):
  """Attention layer that is part of each Transformer layer."""
  hidden_size: int
  hidden_dropout_prob: float
  num_attention_heads: int
  attention_probs_dropout_prob: float
  hidden_dropout_prob: float
  initializer_fn: InitializerType

  @nn.compact
  def __call__(self, q: jnp.ndarray, kv: jnp.ndarray,
               attention_mask: jnp.ndarray,
               deterministic: bool) -> jnp.ndarray:

    attention_output = nn.attention.MultiHeadAttention(
        num_heads=self.num_attention_heads,
        qkv_features=self.hidden_size,
        out_features=None,
        dropout_rate=self.attention_probs_dropout_prob,
        deterministic=deterministic,
        kernel_init=self.initializer_fn,
        bias_init=jax.nn.initializers.zeros,
        name='multi_head_attention',
    )(q, kv, kv, mask=attention_mask)

    attention_output = nn.Dropout(rate=self.hidden_dropout_prob)(
        attention_output, deterministic=deterministic)
    attention_output = nn.LayerNorm(
        epsilon=LAYERNORM_EPSILON, name='attention_output_ln')(
            attention_output + q)

    return attention_output

class GenericTransformerLayer(nn.Module):
  """A single Transformer layer."""
  intermediate_size: int
  hidden_size: int
  hidden_dropout_prob: float
  num_attention_heads: int
  attention_probs_dropout_prob: float
  initializer_fn: InitializerType

  @nn.compact
  def __call__(self, q: jnp.ndarray, kv: jnp.ndarray, mask: jnp.ndarray,
               deterministic: bool) -> jnp.ndarray:
      
    attention_output = CausalAttention(
        hidden_size=self.hidden_size,
        hidden_dropout_prob=self.hidden_dropout_prob,
        num_attention_heads=self.num_attention_heads,
        attention_probs_dropout_prob=self.attention_probs_dropout_prob,
        initializer_fn=self.initializer_fn)(
            q=q, kv=kv, attention_mask=mask,
            deterministic=deterministic)
      
    layer_output = Mlp(
        hidden_size=self.hidden_size,
        hidden_dropout_prob=self.hidden_dropout_prob,
        intermediate_size=self.intermediate_size,
        initializer_fn=self.initializer_fn)(
            attention_output=attention_output, deterministic=deterministic)

    return layer_output

class HollowTransformer(nn.Module):
  """Hollow transformer modified from BERT."""
  vocab_size: int
  hidden_size: int = 768
  num_hidden_layers: int = 12
  num_attention_heads: int = 12
  intermediate_size: int = 3072
  hidden_dropout_prob: float = 0.1
  attention_probs_dropout_prob: float = 0.1
  max_position_embeddings: int = 256
  initializer_range: float = 0.02
  num_layers_per_mixed: int = 4 

  @nn.compact
  def __call__(self,
               input_ids: jnp.ndarray,
               t: float,
               deterministic: bool = True) -> Dict[Text, jnp.ndarray]:

    B, L = input_ids.shape
    # Causal attention doesn't like zero padding
    pad = jnp.zeros((B, 1))
    input_ids = jnp.concatenate([pad, input_ids, pad], axis=1)

    input_ids = input_ids.astype('int32')
    x = Embed(
        embedding_size=self.hidden_size,
        hidden_dropout_prob=self.hidden_dropout_prob,
        vocab_size=self.vocab_size,
        max_position_embeddings=self.max_position_embeddings + 2, # Including the padded values
        initializer_fn=truncated_normal(self.initializer_range))(
            input_ids=input_ids, deterministic=deterministic)
    
    # B, L, K = x.shape
    H = self.num_attention_heads
      
    forward_mask = jnp.tril(jnp.ones((L, L)))
    backward_mask = jnp.triu(jnp.ones((L, L)))
    mixing_mask = jnp.concatenate([forward_mask, backward_mask], axis=-1)
    mixing_mask = jnp.tile(mixing_mask[None, None], (B, H, 1, 1))
    # To impose paramter sharing between the forward and backward causal components
    # we treat the computation
    fb_mask = jnp.block([[forward_mask, jnp.zeros((L, L))], [jnp.zeros((L, L)), backward_mask]])
    fb_mask = jnp.tile(fb_mask[None, None], (B, H, 1, 1))

    # Causal attention doesn't like zero padding
    # pad = jnp.ones((B, 1, K))
    xf = x[:,:-2]
    xb = x[:,2:]
    xm = xf + xb #jnp.concatenate([xf, xb], axis=2)
    xfb = jnp.concatenate([xf, xb], axis=1)
      
    for i in range(self.num_hidden_layers):
      fb_layer = GenericTransformerLayer(
          intermediate_size=self.intermediate_size,
          hidden_size=self.hidden_size,
          hidden_dropout_prob=self.hidden_dropout_prob,
          num_attention_heads=self.num_attention_heads,
          attention_probs_dropout_prob=self.attention_probs_dropout_prob,
          initializer_fn=truncated_normal(self.initializer_range))
      xfb = fb_layer(q=xfb, kv=xfb, mask=fb_mask, deterministic=deterministic)

      if (i + 1) % self.num_layers_per_mixed == 0:
        m_layer = GenericTransformerLayer(
          intermediate_size=self.intermediate_size,
          hidden_size=self.hidden_size, # since we're combining the streams
          hidden_dropout_prob=self.hidden_dropout_prob,
          num_attention_heads=self.num_attention_heads,
          attention_probs_dropout_prob=self.attention_probs_dropout_prob,
          initializer_fn=truncated_normal(self.initializer_range))
        xm = m_layer(q=xm, kv=xfb, mask=mixing_mask, deterministic=deterministic)

    layer_output = xm
      
    word_embedding_matrix = self.variables['params']['Embed_0'][
        'word_embeddings']['embedding']
    logits = MlmLayer(
        hidden_size=self.hidden_size,
        initializer_fn=truncated_normal(self.initializer_range))(
            last_layer=layer_output, embeddings=word_embedding_matrix)

    return logits

In [4]:
k = 8
vocab_size = 1024
seq_len = 10
model = HollowTransformer(
  vocab_size = vocab_size + 1,
  hidden_size = k,
  num_hidden_layers = 6,
  num_attention_heads = 2,
  intermediate_size = 10,
  hidden_dropout_prob = 0.0,
  attention_probs_dropout_prob = 0.0,
  max_position_embeddings = seq_len + 1,
  initializer_range = 1.,#0.02
  num_layers_per_mixed = 3,
)

In [5]:
key = jr.PRNGKey(0)
jax.config.update("jax_debug_nans", False)
jax.config.update("jax_debug_infs", False)

In [11]:
key, _ = jr.split(key)
input_sequence = jr.categorical(logits=jnp.ones((vocab_size,)), shape=(1, seq_len), key=key)
params = model.init(key, input_sequence, 0, True)

# def loss_fn(params):
#     eps = 1e-6
#     out = model.apply(params, input_sequence[0], 0, True)
#     out = out[0]
#     p = jax.nn.softmax(out, axis=-1)
#     x0_one_hot = jax.nn.one_hot(input_sequence, vocab_size + 1)
#     logits = jnp.log(p + eps)
#     return -jnp.mean(x0_one_hot * logits)
    
# grad_fn = jax.grad(loss_fn)
# grads = grad_fn(params)

l = 2

out1 = model.apply(params, input_sequence, 0, True)
input_sequence = input_sequence.at[0, l].set((input_sequence[0, l] - 1) % vocab_size)
out2 = model.apply(params, input_sequence, 0, True)
print(jnp.sum(out1[0] - out2[0], axis=1))

[22.349386  14.366308   0.        -9.03414   -1.1607533 -1.0664959
  0.8421681  0.4240904 -2.1126842  3.6066883]


In [32]:
# Function to count parameters in a frozen dict
def count_parameters(frozen_dict):
    total_params = 0
    for value in frozen_dict.values():
        if isinstance(value, dict):  # If it's a nested dict
            total_params += count_parameters(value)
        else:  # It's an array
            total_params += value.size
    return total_params

# Count the parameters in the 'params' frozen dict
num_params = count_parameters(params)
print(f"Total number of parameters: {num_params}")

Total number of parameters: 177766761


In [30]:
model = HollowTransformer(
    # tpu-v3 has less memory, use smaller network?
    vocab_size=1024 + 1000 + 1, # 1024 tokens, 1000 labels, 1 mask
    hidden_size=768,
    num_hidden_layers=24, # 24
    num_attention_heads=16,
    intermediate_size=3072 // 3,
    hidden_dropout_prob=0.1, 
    attention_probs_dropout_prob=0.1, # Same as hidden dropout prob
    max_position_embeddings=256 + 2, # label at start and end of sequence (because of the 2 streams)
    initializer_range = 1.,
    num_layers_per_mixed=2,
  )
params = model.init(key, input_sequence, 0, True)

In [31]:
# Count the parameters in the 'params' frozen dict
num_params = count_parameters(params)
print(f"Total number of parameters: {num_params}")

Total number of parameters: 144194025


## Simpler parameter sharing

In [59]:
class CausalAttention(nn.Module):
  """Attention layer that is part of each Transformer layer."""
  hidden_size: int
  hidden_dropout_prob: float
  num_attention_heads: int
  attention_probs_dropout_prob: float
  hidden_dropout_prob: float
  initializer_fn: InitializerType

  @nn.compact
  def __call__(self, q: jnp.ndarray, kv: jnp.ndarray,
               attention_mask: jnp.ndarray,
               deterministic: bool) -> jnp.ndarray:

    attention_output = nn.attention.MultiHeadAttention(
        num_heads=self.num_attention_heads,
        qkv_features=self.hidden_size,
        out_features=None,
        dropout_rate=self.attention_probs_dropout_prob,
        deterministic=deterministic,
        kernel_init=self.initializer_fn,
        bias_init=jax.nn.initializers.zeros,
        name='multi_head_attention',
    )(q, kv, kv, mask=attention_mask)

    attention_output = nn.Dropout(rate=self.hidden_dropout_prob)(
        attention_output, deterministic=deterministic)
    attention_output = nn.LayerNorm(
        epsilon=LAYERNORM_EPSILON, name='attention_output_ln')(
            attention_output + q)

    return attention_output

class GenericTransformerLayer(nn.Module):
  """A single Transformer layer."""
  intermediate_size: int
  hidden_size: int
  hidden_dropout_prob: float
  num_attention_heads: int
  attention_probs_dropout_prob: float
  initializer_fn: InitializerType

  @nn.compact
  def __call__(self, q: jnp.ndarray, kv: jnp.ndarray, mask: jnp.ndarray,
               deterministic: bool) -> jnp.ndarray:
      
    attention_output = CausalAttention(
        hidden_size=self.hidden_size,
        hidden_dropout_prob=self.hidden_dropout_prob,
        num_attention_heads=self.num_attention_heads,
        attention_probs_dropout_prob=self.attention_probs_dropout_prob,
        initializer_fn=self.initializer_fn)(
            q=q, kv=kv, attention_mask=mask,
            deterministic=deterministic)
      
    layer_output = Mlp(
        hidden_size=self.hidden_size,
        hidden_dropout_prob=self.hidden_dropout_prob,
        intermediate_size=self.intermediate_size,
        initializer_fn=self.initializer_fn)(
            attention_output=attention_output, deterministic=deterministic)

    return layer_output

class HollowTransformer(nn.Module):
  """Hollow transformer modified from BERT."""
  vocab_size: int
  hidden_size: int = 768
  num_hidden_layers: int = 12
  num_attention_heads: int = 12
  intermediate_size: int = 3072
  hidden_dropout_prob: float = 0.1
  attention_probs_dropout_prob: float = 0.1
  max_position_embeddings: int = 256
  initializer_range: float = 0.02
  num_layers_per_mixed: int = 4 

  @nn.compact
  def __call__(self,
               input_ids: jnp.ndarray,
               t: float, # This is not currently used
               deterministic: bool = True) -> Dict[Text, jnp.ndarray]:

    B, L = input_ids.shape
    pad = jnp.zeros((B, 1))
    input_ids = jnp.concatenate([pad, input_ids, pad], axis=1)

    input_ids = input_ids.astype('int32')
    x = Embed(
        embedding_size=self.hidden_size,
        hidden_dropout_prob=self.hidden_dropout_prob,
        vocab_size=self.vocab_size,
        max_position_embeddings=self.max_position_embeddings + 2, # Including the padded values
        initializer_fn=truncated_normal(self.initializer_range))(
            input_ids=input_ids, deterministic=deterministic)
    
    H = self.num_attention_heads
      
    forward_mask = jnp.tile(jnp.tril(jnp.ones((L, L)))[None, None], (B, H, 1, 1))
    backward_mask = jnp.tile(jnp.triu(jnp.ones((L, L)))[None, None], (B, H, 1, 1))
    mixing_mask = jnp.concatenate([forward_mask, backward_mask], axis=-1)   

    xf = x[:,:-2]
    xb = x[:,2:]
    xm = None
      
    for i in range(self.num_hidden_layers):
      f_layer = GenericTransformerLayer(
          intermediate_size=self.intermediate_size,
          hidden_size=self.hidden_size,
          hidden_dropout_prob=self.hidden_dropout_prob,
          num_attention_heads=self.num_attention_heads,
          attention_probs_dropout_prob=self.attention_probs_dropout_prob,
          initializer_fn=truncated_normal(self.initializer_range))
      # b_layer = GenericTransformerLayer(
      #     intermediate_size=self.intermediate_size,
      #     hidden_size=self.hidden_size,
      #     hidden_dropout_prob=self.hidden_dropout_prob,
      #     num_attention_heads=self.num_attention_heads,
      #     attention_probs_dropout_prob=self.attention_probs_dropout_prob,
      #     initializer_fn=truncated_normal(self.initializer_range))
      xf = f_layer(q=xf, kv=xf, mask=forward_mask, deterministic=deterministic)
      xb = f_layer(q=xb, kv=xb, mask=backward_mask, deterministic=deterministic)

      if (i + 1) % self.num_layers_per_mixed == 0:
        if xm is None:
            xm = jnp.concatenate([xf, xb], axis=2)
        xfb = jnp.concatenate([xf, xb], axis=1)
        m_layer = GenericTransformerLayer(
          intermediate_size=self.intermediate_size,
          hidden_size=self.hidden_size * 2, # since we're combining the streams
          hidden_dropout_prob=self.hidden_dropout_prob,
          num_attention_heads=self.num_attention_heads,
          attention_probs_dropout_prob=self.attention_probs_dropout_prob,
          initializer_fn=truncated_normal(self.initializer_range))
        xm = m_layer(q=xm, kv=xfb, mask=mixing_mask, deterministic=deterministic)

    layer_output = xm
      
    word_embedding_matrix = self.variables['params']['Embed_0'][
        'word_embeddings']['embedding']
    logits = MlmLayer(
        hidden_size=self.hidden_size,
        initializer_fn=truncated_normal(self.initializer_range))(
            last_layer=layer_output, embeddings=word_embedding_matrix)

    return logits

In [8]:
# Testing the hollowness
k = 8
vocab_size = 1024
seq_len = 10
model = HollowTransformer(
  vocab_size = vocab_size + 1,
  hidden_size = k,
  num_hidden_layers = 6,
  num_attention_heads = 2,
  intermediate_size = 10,
  hidden_dropout_prob = 0.0,
  attention_probs_dropout_prob = 0.0,
  max_position_embeddings = seq_len + 1,
  initializer_range = 1.,#0.02
  num_layers_per_mixed = 3,
)

key, _ = jr.split(key)
input_sequence = jr.categorical(logits=jnp.ones((vocab_size,)), shape=(1, seq_len), key=key)
params = model.init(key, input_sequence, 0, True)

# def loss_fn(params):
#     eps = 1e-6
#     out = model.apply(params, input_sequence[0], 0, True)
#     out = out[0]
#     p = jax.nn.softmax(out, axis=-1)
#     x0_one_hot = jax.nn.one_hot(input_sequence, vocab_size + 1)
#     logits = jnp.log(p + eps)
#     return -jnp.mean(x0_one_hot * logits)
    
# grad_fn = jax.grad(loss_fn)
# grads = grad_fn(params)

l = 4

out1 = model.apply(params, input_sequence, 0, True)
input_sequence = input_sequence.at[0, l].set((input_sequence[0, l] - 1) % vocab_size)
out2 = model.apply(params, input_sequence, 0, True)
print(jnp.sum(out1[0] - out2[0], axis=1))

NameError: name 'key' is not defined

In [72]:
input_sequence = jr.categorical(logits=jnp.ones((vocab_size,)), shape=(1, seq_len), key=key)

model = HollowTransformer(
    # tpu-v3 has less memory, use smaller network?
    vocab_size=1024 + 1000 + 1, # 1024 tokens, 1000 labels, 1 mask
    hidden_size=768,
    num_hidden_layers=24, # 24
    num_attention_heads=16,
    intermediate_size=1280,
    hidden_dropout_prob=0.1, 
    attention_probs_dropout_prob=0.1, # Same as hidden dropout prob
    max_position_embeddings=256 + 2, # label at start and end of sequence (because of the 2 streams)
    initializer_range = 1.,
    num_layers_per_mixed=4,
  )
params = model.init(jr.PRNGKey(0), input_sequence, 0, True)

In [73]:
num_params = count_parameters(params)
print(f"Total number of parameters without concat or sharing: {num_params}")

Total number of parameters without concat or sharing: 173096937


In [14]:
# Count the parameters in the 'params' frozen dict
num_params = count_parameters(params)
print(f"Total number of parameters without parameter sharing: {num_params}")

Total number of parameters without parameter sharing: 202303465


# Testing the new hollow transformer based on MD4

In [2]:
%cd ~/md4
%ls

/home/yixiuz/md4
CONTRIBUTING.md  expt/                        requirements_tpu.txt
LICENSE          md4/                         run_gcp.sh
README.md        prepare_openwebtext_data.py  text_parameter_count.ipynb
data_dir/        requirements_gpu.txt         wandb/


/home/yixiuz/md4_venv/lib/python3.12/site-packages/IPython/core/magics/osm.py:393: UserWarning: This is now an optional IPython functionality, using bookmarks requires you to install the `pickleshare` library.
  bkms = self.shell.db.get('bookmarks', {})
/home/yixiuz/md4_venv/lib/python3.12/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [9]:
from importlib import reload
reload(hollow_transformer)

<module 'md4.networks.hollow_transformer' from '/home/yixiuz/md4/md4/networks/hollow_transformer.py'>

In [10]:
from flax import linen as nn
import jax
import jax.numpy as jnp
import jax.random as jr

from md4.networks import hollow_transformer

In [11]:
vocab_size = 5

args=hollow_transformer.ModelArgs(
            dim=8 * 2,
            n_layers=4,
            n_heads=2,
            n_kv_heads=2,
            output_channels=vocab_size,
            multiple_of=2,
            dropout_rate=0.0,
            depth_scaled_init=False,
            mlp_type='swiglu',
            cond_type='adaln',
            embed_input=True,
            n_embed_classes=vocab_size + 1,
            n_layers_per_mixed=1
        )
model = hollow_transformer.HollowTransformer(args)

In [13]:
key = jr.PRNGKey(0)
jax.config.update("jax_debug_nans", True)
jax.config.update("jax_debug_infs", False)

seq_len = 10

key, _ = jr.split(key)
input_sequence = jr.categorical(logits=jnp.ones((vocab_size,)), shape=(1, seq_len), key=key)
# input_sequence = jr.uniform(shape=(1, seq_len, vocab_size), key=key)
params = model.init(key, input_sequence, train=True)

l = 4

out1 = model.apply(params, input_sequence, train=True)
input_sequence = input_sequence.at[0, l].set((input_sequence[0, l] - 1) % vocab_size)
out2 = model.apply(params, input_sequence, train=True)
print(jnp.sum(out1[0] - out2[0], axis=1))

[-1.4137759   0.15288448  1.8202124   3.013166    0.         -5.5674944
 -2.3956242  -1.5285606   3.6555443   7.256277  ]


In [124]:
%debug

> /home/yixiuz/md4/md4/networks/transformer.py(93)reshape_for_broadcast()
     91   ndim = x.ndim
     92   assert 1 < ndim
---> 93   assert freqs_cis.shape == (x.shape[1], x.shape[-1])
     94   shape = [d if i == 1 or i == ndim - 1 else 1 for i, d in enumerate(x.shape)]
     95   return freqs_cis.reshape(shape)



ipdb>  x.shape


(1, 20, 2, 4)


ipdb>  freqs_cis.shape


(10, 8)


ipdb>  exit


In [104]:
input_sequence = input_sequence.at[0, l].set((input_sequence[0, l] - 1) % vocab_size)
input_sequence

Array([[0, 3, 2, 3, 1, 4, 1, 0, 2, 1]], dtype=int32)